### ISSUE TITLE
type error getClusterExpansionZoom  

### ISSUE THREAD

**Issue by garytube** [leighhalliday/use-supercluster#10]
I have a hard time making Typescript happy (warning - im new to typescript)

```(parameter) cluster: Supercluster.PointFeature<Supercluster.AnyProps> | Supercluster.PointFeature<Supercluster.ClusterProperties & Supercluster.AnyProps>
Argument of type 'string | number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.ts(2345)

getClusterExpansionZoom(cluster.id)
```

I assume this is because of this 

```
// index.d.ts
type PointFeature<P> = GeoJSON.Feature<GeoJSON.Point, P>;  // defines [id] as   string | number
```

So should it rather be something like this

`getClusterExpansionZoom(cluster.properties.cluster_id)  // makes tslint happy` 

This tripped me of while doing your tutorial which is otherwise fantastic.

Thank you

**Comment by riccardocaranfil** [comment]
Hey @garytube, where are you calling the `getClusterExpansionZoom(cluster.id)` method? Can you show mode code?

**Comment by garytube** [comment]
Sure.
https://www.github.com/garytube/weddingweiser_map/tree/main/components%2Fmap%2FMap.tsx

In calling it inside the clusters.map function

**Comment by leighhalliday** [comment]
@garytube I think it's because the `clusters` value that comes from the supercluster library itself is an array of `Supercluster.ClusterFeature<C> | Supercluster.PointFeature<P>`... and unfortunately the `isCluster` property isn't enough for TS to know if you're dealing with a `ClusterFeature` or a `PointFeature`. I don't have a great suggestion for you, although I think your solution works.

Do you have an idea? I'm somewhat limited by what supercluster returns, since this package is just the glue between React and Supercluster itself.
